### ISSUE TITLE
ライブラリ・モジュールの記述

### ISSUE THREAD

**Issue by c0a2103365** [Ryo-Miyakawa/ProjExD#10]
https://github.com/Ryo-Miyakawa/ProjExD/blob/c9e5bdb9171f562e0c7634f2abdd18db3ad77e55/ex05/dodge_bomb.py#L1
標準ライブラリは標準ライブラリでまとめ、外部ライブラリは外部ライブラリでまとめたほうが良いでしょう。
例）（標準ライブラリ）
       import os
       import sys
　　（外部ライブラリ）
       import pygame as pg

**Comment by Ryo-Miyakawa** [comment]
コメントありがとうございます。修正しました。
