### ISSUE TITLE
数字だけじゃ無くて～秒とか，～ｓとかつけられますか？

### ISSUE THREAD

**Issue by c0a21065a6** [Ryo-Miyakawa/ProjExD#7]
https://github.com/Ryo-Miyakawa/ProjExD/blob/82c4e340146119394e71fe4f58d66cb08eb70d67/ex03-2/maze.py#L54

**Comment by Ryo-Miyakawa** [comment]
コメントありがとうございます。すみません、技術不足でできませんでした。
