### ISSUE TITLE
改行について

### ISSUE THREAD

**Issue by linyinjun** [Ryo-Miyakawa/ProjExD#9]
https://github.com/Ryo-Miyakawa/ProjExD/blob/a067ae135e4498cdfb5dec3a512a27a53fb9f1eb/ex04/dodge_bomb.py#L70

ifは一行にまとめと方が良いかもしれません
要らないスペースがを消した方がいいと思う

**Comment by Ryo-Miyakawa** [comment]
コメントありがとうございます。いらない改行やスペースを削除しました。if文については時間のあるときに修正したいと思います。
